---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1s0hptapqxud0jyrshurm6ycru3gekuuauhdfdsjgypsqq70gc92qr66jr2
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1s0hptapqxud0jyrshurm6ycru3gekuuauhdfdsjgypsqq70gc92qr66jr2
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1s0hptapqxud0jyrshurm6ycru3gekuuauhdfdsjgypsqq70gc92qr66jr2
