apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Ocyb4pioWh+00FdaZIk/xNS/CzHvLNCQi4Z6qzpuFjufTfJ/Wl5rXA==,iv:hbSdDxzpoJBGfNwcB6WPT7E9vHQPNGHKjKc7hXbixBU=,tag:Bbfofnt+HnylsoRkjoRMdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0hptapqxud0jyrshurm6ycru3gekuuauhdfdsjgypsqq70gc92qr66jr2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT0dhOVVWeHRpUmpDNlky
            ay9yWkxUZnJGZzNiWm03SzFLRENGODErWDJrClRzWGd3L3lnbVRWaUxCTCtibUZB
            RkVldWhuSnBDQWJLS2I3enAzeTdBbkkKLS0tIGdqWUc0ZTFXdlBkZlNDaXprazlk
            aEhVdFl0M1kxU0w4UFc4OUlmamJLMGcKHnnRpy/HyDXCBEVTWKn4z6eSMFwnL92L
            ATElOpi5rnsNbVG6ntRBT1oW86KIQzhp61VPw/PPRQxnXzk39uQOUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T06:25:03Z"
    mac: ENC[AES256_GCM,data:8Ds27Ws+tWJQMTJdy0HvjBGrn52BO8YXsSjUdPh8rKiFhD8/NHTEa8m8Uo+DB0Vy+Roj9UwXGNk05pyaiFAGcgGlCaIvPtZEKivzM1jjZtfc9aSAVMR+1VH95gm5wSIb5pdHtAAJrzWnZ0B+8Mx3hCzG5tZAdzVCYA3sH+OzfA4=,iv:weYG9lJJke5pW2Dp7t7B9kcWw3iDD7Getzp7NWcMBLI=,tag:6n7m01ye+KUQJTdcFWL+KQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
